### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by croutee** [greeness/yahtzee-optimal-strategy#1]
Hi,

I'm reading your code. Good Job.

Now, I'm trying to launch sim_game.py and obtained this error : 
Traceback (most recent call last):
  File "C:\Users\sc\yahtzee\yahtzee-optimal-strategy-master\yahtzee-optimal-strategy-master\sim_game.py", line 85, in <module>
    load_expectation()
  File "C:\Users\sc\yahtzee\yahtzee-optimal-strategy-master\yahtzee-optimal-strategy-master\widget.py", line 259, in load_expectation
    E0 = json.load(open('./data/exp%s.json' % timestamp))
IOError: [Errno 2] No such file or directory: './data/exp.json'

And with sim_game_with_cache : 
Traceback (most recent call last):
  File "C:\Users\sc\yahtzee\yahtzee-optimal-strategy-master\yahtzee-optimal-strategy-master\sim_game_with_cache.py", line 237, in <module>
    load_optimal_strategy()
  File "C:\Users\sc\yahtzee\yahtzee-optimal-strategy-master\yahtzee-optimal-strategy-master\sim_game_with_cache.py", line 40, in load_optimal_strategy
    id_to_state_json = json.load(open('./data/id_to_state.json'))
IOError: [Errno 2] No such file or directory: './data/id_to_state.json'

What is the job of these files ? Where can I obtain them ?

Thanks a lot !

Regards.

Croutee

**Comment by gaznu** [comment]
Hi,

Same problem here. If these files could be included, that would really help trying out your implementation. Right now it is not accessible (to me).

Regards

**Comment by gerwin3** [comment]
You need to do generate the expectation files yourself:

1. mkdir data
2. uncomment line widget.py:372 (e.g. call to training_expectation())
3. run widget.py to generate expectation files

**Comment by gerwin3** [comment]
I created a pull request with working changes here: https://github.com/greeness/yahtzee-optimal-strategy/pull/2

Should allow for generating the files (though it takes a long time).
